### ISSUE TITLE
FontAwesome 6.1

### ISSUE THREAD

**Issue by brandonfancher** [gofractally/fractally#21]
We'd like to use FontAwesome 6 (6.1) icons, and while `react-icons` is super convenient and easy to work with, it only supports the older FontAwesome 5 icons. `react-icons` does provide ways to add support for other icon sets in our application, however.

This task is (potentially) multi-part:

- [ ] What is the best way to support FA6? Assess the viability (and roughly estimate effort) around adding support for FA6 icons in our application via `react-icons`. Can we support the full iconset, or should we add support manually for just the icons we want to use? Maybe we should just use the SVGs and create our own component wrapper? Or maybe there's a better FA6 react package available?
- [ ] After discussing, implement whatever solution we think is best.

**Comment by sparkplug0025** [comment]
Please check my draft here #25
